name: Run .NET tests and upload TRX

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test (produce TRX)
        run: dotnet test --no-build --configuration Release --logger 
"trx;LogFileName=TestResults.trx" --results-directory TestResults

      - name: Upload TRX results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
          if-no-files-found: warn
          retention-days: 7

